### PR TITLE
Upgrade for use with hapi v17

### LINKED ISSUE #33: Hapi v17 Support
### Overview
If you are not aware yet, Hapi v17 is making the transition from callbacks to `async`/`await`, as well as deprecating some other rarely used functionality. This is a breaking change that may make your plugin no longer compatible with the Hapi API.

#### Changelog
Draft release notes can be found here: https://github.com/hapijs/hapi/issues/3658

#### Target Release
The target release date for v17 is the beginning of *November*.

### Tasks
- [ ] Reply to this to acknowledge that you are actively maintaining this module and are willing to update it
- [ ] Update plugin to be fully `async`/`await` compatible using the `v17` branch from Hapi for testing
  #### Possible dev flow for updating
  - Clone Hapi
  - `npm link` within the Hapi repo
  - `npm link hapi` within your plugin repo
  - Your plugin will now be using `v17` of Hapi branch for tests
- [ ] Release new major version of your plugin on `npm`. Please use a major version increment as this will be a breaking change and it would be terrible for it to sneak into current versions of Hapi.

### Notes
* Support is being dropped for all versions of Node `<8.0.0`. 
* Hapi `v16` will continue to be supported for as long as there exists a Node LTS actively being supported that is not compatible with `v17`.
* Targeted release date is November 1st, 2017. Please try to have your plugin updated before then.
* This issue is being opened because your plugin is listed on the official hapi website

### PR DESCRIPTION
**Pull request by devinivy**
Resolves #33 

- [x] Update to match hapi v17 API
- [x] All async/await, remove callback interface
- [x] Update to haute v2, with improved error messages (e.g. "`server.route()...`" vs. "`instance.route()...`")
- [x] Remove support for dogwater, loveboat, and chairo
- [x] Add support for schmervice

### CODE REVIEW

**Comment by jamesdixon** [comment]
@devinivy should I give this a try?

**Comment by devinivy** [comment]
@jamesdixon go for it!

**Comment by jamesdixon** [comment]
@devinivy will do! I'm not sure I'll have it going before Monday. My application is very much a hodge podge of structures from the past, so I'd imagine this will take me a while to implement. That said, looking forward to having a more organized application.

Thx for your work on this!

**Comment by devinivy** [comment]
No sweat!  It will land very soon either way.  🍻

**Pull request merged**
